{% set data = load_setup_py_data() %}

package:
    name: bsread
    version: {{ data["version"] }}

about:
   home: {{ data["url"] }}
   summary: {{ data["description"] }}

source:
    path: ..

build:
    noarch: python
    number: 0
    script: python -m pip install --no-deps --ignore-installed .
    entry_points:
        - bs = bsread.cli.bs:main

requirements:
    build:
        - python >=3.6
        - setuptools
        - pip
    run:
        - python >=3.6
        - mflow >=0.2.0
        - bitshuffle
        - numpy
        - pyzmq
        - requests
        - click

