package:
    name: bsread
    version: "{{ load_setup_py_data().version }}"
#source:
#    git_tag: 0.0.14
#    git_url: git@git.psi.ch:sf_daq/bsread_python.git
source:
    path: ..

build:
    noarch: python
    number: 0
    script: python -m pip install --no-deps --ignore-installed .
    entry_points:
        - bs = bsread.cli.bs:main

requirements:
    build:
        - python >=3.6
        - setuptools
        - pip
    run:
        - python >=3.6
        - mflow >=0.2.0
        - bitshuffle
        - numpy
        - pyzmq
        - requests
        - click

about:
    home: git@git.psi.ch:sf_daq/bsread_python.git
    summary: "BSREAD Python library."
