
name: conda_publish

on:
  release:
    types: [published, edited]
  workflow_dispatch:
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: publish-to-conda
      uses: paulscherrerinstitute/conda-publish-action@master
      with:
        subdir: 'conda-recipe'
        anacondatoken: ${{ secrets.ANACONDA_TOKEN }}
        channel_opts: '-c paulscherrerinstitute'
